easy_scrum_easy_scrum:
    resource: "@EasyScrumEasyScrumBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#fos_user_group:
    #resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    #prefix: dashboard/group
