<?php

namespace EasyScrum\EasyScrumBundle\Repository;

/**
 * Product_BacklogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_BacklogRepository extends \Doctrine\ORM\EntityRepository
{
}
