<?php

namespace EasyScrum\EasyScrumBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
  public function findProjectByName($name){
    $queryBuilder = $this->createQueryBuilder('p')
                  ->where('p.nom = :name')
                  ->setParameter('name', $name) ;
    return $queryBuilder->getQuery()->getResult() ;
  }
  public function findProjectById($id){
    $queryBuilder = $this->createQueryBuilder('p')
                  ->where('p.id = :id')
                  ->setParameter('id', $id) ;
    return $queryBuilder->getQuery()->getResult() ;
  }
  public function findProjectsByUser($user){

    $queryBuilder = $this->createQueryBuilder('p')
                  ->where('p.productOwner = :user')
                  ->setParameter('user' , $user);
    return $queryBuilder->getQuery()->getResult();

  }
  public function findProjectByName_user($user, $nom){
    $queryBuilder = $this->createQueryBuilder('p')
                    ->where('p.productOwner = :user')
                    ->setParameter('user', $user)
                    ->andWhere('p.nom = :nom')
                    ->setParameter('nom' , $nom);
    return $queryBuilder->getQuery()->getOneOrNullResult();

  }
}
