<?php

namespace EasyScrum\EasyScrumBundle\Repository;

/**
 * Release1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Release1Repository extends \Doctrine\ORM\EntityRepository
{
  public function findReleaseByProject_name($project, $name){
    $queryBuilder = $this->createQueryBuilder('r')
                    ->where('r.projet = :project')
                    ->setParameter('project', $project)
                    ->andWhere('r.nom = :nom')
                    ->setParameter('nom' , $name);
    return $queryBuilder->getQuery()->getOneOrNullResult();

  }
}
