<?php

namespace EasyScrum\EasyScrumBundle\Repository;

/**
 * SprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprintRepository extends \Doctrine\ORM\EntityRepository
{
  public function findSprintByRlease_name($release, $name){
    $queryBuilder = $this->createQueryBuilder('s')
                    ->where('s.release = :release')
                    ->setParameter('release', $release)
                    ->andWhere('s.name = :name')
                    ->setParameter('name' , $name);
    return $queryBuilder->getQuery()->getOneOrNullResult();

  }
}
