<?php

namespace EasyScrum\EasyScrumBundle\Repository;

/**
 * TaskStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskStageRepository extends \Doctrine\ORM\EntityRepository
{
}
