<?php

namespace EasyScrum\EasyScrumBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
  public function findTeamByNom_admin($admin, $nom){
    $queryBuilder = $this->createQueryBuilder('t')
                    ->where('t.admin = :admin')
                    ->setParameter('admin', $admin)
                    ->andWhere('t.nom = :nom')
                    ->setParameter('nom' , $nom);
    return $queryBuilder->getQuery()->getOneOrNullResult();

  }
}
