<?php

namespace EasyScrum\EasyScrumBundle\Repository;

/**
 * UserStoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStoryRepository extends \Doctrine\ORM\EntityRepository
{
}
