easy_scrum_easy_scrum_homepage:
    path:     /
    defaults: { _controller: EasyScrumEasyScrumBundle:Default:index }
easy_scrum_dashbord:
    path: /dashboard
    defaults: { _controller: EasyScrumEasyScrumBundle:Default:dashboard}
show_projets:
  path: /dashboard/projets
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:showProjects }

show_projets_list:
  path: /dashboard/projets/list
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:showProjectsList }

project_create:
  path: /dashboard/createProject
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:create }


project_edit:
  path: /dashboard/projets/edit
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:editProject }

project_view :
  path: /dashboard/projets/{id}
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:showProject }

project_archive :
  path : /dashboard/archive
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:archive}
project_active :
  path : /dashboard/active
  defaults : { _controller: EasyScrumEasyScrumBundle:Projet:active}

show_archive :
  path : /dashboard/archivedProjects
  defaults : { _controller: EasyScrumEasyScrumBundle:Projet:showArchive}
project_delete :
  path : /dashboard/delete
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:delete}
release_create:
    path: /dashboard/projets/releases/createRelease
    defaults: { _controller: EasyScrumEasyScrumBundle:Release:create }
release_edit:
    path: /dashboard/projets/release/edit
    defaults: { _controller: EasyScrumEasyScrumBundle:Release:edit}
release_delete:
    path: /dashboard/projects/releases/delete
    defaults: { _controller: EasyScrumEasyScrumBundle:Release:delete}
show_teams:
    path: /dashboard/teams
    defaults: { _controller: EasyScrumEasyScrumBundle:Team:showTeams}

team_create:
    path: /dashboard/teams/createTeam
    defaults: { _controller: EasyScrumEasyScrumBundle:Team:create }
add_friend:
    path: /dashboard/teams/addFriend
    defaults: { _controller: EasyScrumEasyScrumBundle:User:addFriend}

sprint_create:
    path:     /dashboard/sprints/create
    defaults: { _controller: EasyScrumEasyScrumBundle:Sprint:create }

userStory_create:
    path:     /dashboard/userStrories/create
    defaults: { _controller: EasyScrumEasyScrumBundle:UserStory:create }

task_create:
    path:     /dashboard/tasks/create
    defaults: { _controller: EasyScrumEasyScrumBundle:Task:create }
