easy_scrum_easy_scrum_homepage:
    path:     /
    defaults: { _controller: EasyScrumEasyScrumBundle:Default:index }
easy_scrum_dashbord:
    path: /dashboard
    defaults: { _controller: EasyScrumEasyScrumBundle:Default:dashboard}
show_projets:
  path: /dashboard/projets
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:showProjects }

show_projets_list:
  path: /dashboard/projets/list
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:showProjectsList }

project_create:
  path: /dashboard/createProject
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:create }


project_edit:
  path: /dashboard/projets/{name}/edit
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:editProject }

project_view :
  path: /dashboard/projets/{id}
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:showProject }


release_create:
    path: /dashboard/projets/{id}/releases/createRelease
    defaults: { _controller: EasyScrumEasyScrumBundle:Release:create }

show_teams:
    path: /dashboard/teams
    defaults: { _controller: EasyScrumEasyScrumBundle:Team:showTeams}

team_create:
    path: /dashboard/teams/createTeam
    defaults: { _controller: EasyScrumEasyScrumBundle:Team:create }
add_friend:
    path: /dashboard/teams/addFriend
    defaults: { _controller: EasyScrumEasyScrumBundle:User:addFriend}
