easy_scrum_easy_scrum_homepage:
    path:     /
    defaults: { _controller: EasyScrumEasyScrumBundle:Default:index }
easy_scrum_dashbord:
    path: /dashboard
    defaults: { _controller: EasyScrumEasyScrumBundle:Default:dashboard}
show_projets:
  path: /dashboard/projets
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:showProjects }

show_projets_list:
  path: /dashboard/projets/list
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:showProjectsList }
project_create:
  path: /dashboard/createProject
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:Create}
project_view:
  path: /dashboard/projets/{id}
  defaults: { _controller: EasyScrumEasyScrumBundle:Projet:projetView }
  requirements:
    id : \d+
